environment:
  nodejs_version: "10"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test:cli
  - node tests\run_e2e.js --appveyor "--glob=tests/{basic,commands,generate,build/styles}/**"

build: off
deploy: off
shallow_clone: true

cache:
  - node_modules -> package-lock.json
