name: DevInfra

# Declare default permissions as read only.
permissions:
  contents: read

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - uses: angular/dev-infra/github-actions/commit-message-based-labels@223f927699fe366d2d68fde745fe2caa7e031fd1
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
