name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  commit_message_based_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: angular/dev-infra/github-actions/commit-message-based-labels@6fb5d7162863b67cd1e006b2262db7da78608c88
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
