name: Lock Inactive Issues

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@8be6f887e59710eba16e19539cc99127b0e68936
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
