name: Lock Inactive Issues

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@39af989a0862e684b7f4934fd6a61be6bc65f423
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
