name: Lock Inactive Issues

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@a87135ebb421b291f986ec2c673e9c37f22dfc17
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
