name: Lock Inactive Issues

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@a0ce99e81ce72091d7900a5ac054172d1aaec19e
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
