name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  analyze:
    runs-on: ubuntu-latest
    outputs:
      snapshots: ${{ steps.filter.outputs.snapshots }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            snapshots:
              - 'tests/legacy-cli/e2e/ng-snapshot/package.json'

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Setup ESLint Caching
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .eslintcache
          key: ${{ runner.os }}-${{ hashFiles('.eslintrc.json') }}
      - name: Install node modules
        run: yarn install --immutable
      - name: Run ESLint
        run: yarn lint --cache-strategy content
      - name: Validate NgBot Configuration
        run: yarn ng-dev ngbot verify
      - name: Validate Circular Dependencies
        run: yarn ts-circular-deps check
      - name: Run Validation
        run: yarn admin validate
      - name: Check Package Licenses
        uses: actions/dependency-review-action@72eb03d02c7872a771aacd928f3123ac62ad6d3a # v4.3.3
        with:
          config-file: './.github/dependency-review-config.yml'
      - name: Check tooling setup
        run: yarn check-tooling-setup
      - name: Check commit message
        # Commit message validation is only done on pull requests as its too late to validate once
        # it has been merged.
        run: yarn ng-dev commit-message validate-range ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
      - name: Check code format
        # Code formatting checks are only done on pull requests as its too late to validate once
        # it has been merged.
        run: yarn ng-dev format changed --check ${{ github.event.pull_request.base.sha }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Install node modules
        run: yarn install --immutable
      - name: Build release targets
        run: yarn ng-dev release build
      - name: Store PR release packages
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: packages
          path: dist/releases/*.tgz
          retention-days: 14

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Install node modules
        run: yarn install --immutable
      - name: Run module tests
        run: yarn bazel test //modules/...
      - name: Run package tests
        run: yarn bazel test //packages/...

  e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20, 22]
        subset: [npm, yarn, esbuild]
        shard: [0, 1, 2, 3, 4, 5]
        exclude:
          # Exclude Node.js v18 when running on a PR
          - node: ${{ github.event_name != 'pull_request' && 'none' || '18' }}
          # Exclude Node.js v20 when running on a PR
          - node: ${{ github.event_name != 'pull_request' && 'none' || '20' }}
          # Exclude Windows when running on a PR
          - os: ${{ github.event_name != 'pull_request' && 'none' || 'windows-latest' }}
          # Skip yarn subset on Windows
          - os: windows-latest
            subset: yarn
          # Skip Node.js v18 tests on Windows
          - os: windows-latest
            node: 18
          # Skip Node.js v20 tests on Windows
          - os: windows-latest
            node: 20
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Install node modules
        run: yarn install --immutable
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Run CLI E2E tests
        run: yarn bazel test --define=E2E_SHARD_TOTAL=6 --define=E2E_SHARD_INDEX=${{ matrix.shard }} --config=e2e //tests/legacy-cli:e2e.${{ matrix.subset }}_node${{ matrix.node }}

  e2e-snapshots:
    needs: analyze
    if: needs.analyze.outputs.snapshots == 'true'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18]
        subset: [npm, yarn, esbuild]
        shard: [0, 1, 2, 3, 4, 5]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Install node modules
        run: yarn install --immutable
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@03b8a7dffd1205e061f0bee949024ebefc2a6592
      - name: Run CLI E2E tests
        run: yarn bazel test --define=E2E_SHARD_TOTAL=6 --define=E2E_SHARD_INDEX=${{ matrix.shard }} --config=e2e //tests/legacy-cli:e2e.snapshots.${{ matrix.subset }}_node${{ matrix.node }}
