name: OpenSSF Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '0 2 * * 0'
  push:
    branches: [master]
  workflow_dispatch:

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      actions: read
      contents: read

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
        with:
          persist-credentials: false

      - name: 'Run analysis'
        uses: ossf/scorecard-action@b614d455ee90608b5e36e3299cd50d457eb37d5f # renovate: tag=v1.0.3
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: true

      # Upload the results as artifacts.
      - name: 'Upload artifact'
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # renovate: tag=v2.3.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      # Upload the results to GitHub's code scanning dashboard.
      - name: 'Upload to code-scanning'
        uses: github/codeql-action/upload-sarif@474bbf07f9247ffe1856c6a0f94aeeb10e7afee6 # renovate: tag=v1.1.0
        with:
          sarif_file: results.sarif
